openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://customer-database-management.test'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/customers:
    get:
      summary: ''
      operationId: getApiCustomers
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiCustomers
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: voluptates
                  nullable: false
                last_name:
                  type: string
                  description: ''
                  example: voluptas
                  nullable: false
                age:
                  type: integer
                  description: ''
                  example: 19
                  nullable: false
                dob:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2025-01-12T13:29:06'
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: pkoepp@example.com
                  nullable: false
              required:
                - first_name
                - last_name
                - age
                - dob
                - email
      security: []
  '/api/customers/{id}':
    get:
      summary: ''
      operationId: getApiCustomersId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiCustomersId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: exercitationem
                  nullable: false
                last_name:
                  type: string
                  description: ''
                  example: vitae
                  nullable: false
                age:
                  type: integer
                  description: ''
                  example: 15
                  nullable: false
                dob:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2025-01-12T13:29:06'
                  nullable: false
                email:
                  type: string
                  description: ''
                  example: null
                  nullable: false
              required:
                - first_name
                - last_name
                - age
                - dob
      security: []
    delete:
      summary: ''
      operationId: deleteApiCustomersId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the customer.'
        example: ullam
        required: true
        schema:
          type: string
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: fadel.carson@example.net
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: 'lN|esJN4{MeG!<o@6y'
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: kifqtqltrwgwnebnxbwvcko
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: allene.jerde@example.net
                  nullable: false
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: 'i1)!yTAd:jm'
                  nullable: false
              required:
                - name
                - email
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
